### ISSUE TITLE
sanity_var check is failing with correctly set variables

### ISSUE THREAD

**Issue by andrewmackrodt** [tiredofit/docker-nginx-proxy-cloudflare-companion#3]
This issue only happens in the `latest` tag, `3.0` works correctly. I have my environment variables defined in `.env` which is in the same directory as `docker-compose.yml`, everything is defined correctly, however, upon container start I get the error:

```
[cont-init.d] 10-cloudflare-companion: executing... 
cloudflare     | [ERROR] ** [nginx-proxy-cloudflare-companion] No 'Cloudflare Email' Entered! - Set '$email@domain.com'
```
Where "email@domain.com" is my correct e-mail address.

**Comment by tiredofit** [comment]
Thanks for submitting. I'll review this and fix up latest.

**Comment by tiredofit** [comment]
A new `latest` or `3.1.1` will resolve this issue. I've also removed the requirement to have CF_EMAIL as there are some cases that you can get by with it being blank using specific tokens. `3.1.2` runs on Alpine 3.12 now as well, but won't make a difference in the operation of the image.

**Comment by andrewmackrodt** [comment]
Just pulled latest and confirmed working, thanks for the quick fix!
